### ISSUE TITLE
Two change listeners

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/sprouts#42]
When we create a view via `viewAs`, `view` or `viewAsNullable`, we always subscribe to changes twice.
Once by adding an onChange listener and once by adding a consumer to the `_viewers` list.

```Java
final Var<@Nullable U> var = ...

onChange(DEFAULT_CHANNEL, v -> var.set( ... );
_viewers.add(v -> var.set(From.VIEW, ...);

return var;
```
Is there a reason for this?

**Comment by Gleethos** [comment]
I don't remember why it is there...
But reading through the code and playing around with it a bit 
I honestly don't see a reason for its existence.

I will remove the second change listener list.

**Comment by Gleethos** [comment]
Thanks for spotting this!!!
