### ISSUE TITLE
Calling Set Null no longer Compiles under NullAway

### ISSUE THREAD

**Issue by Gleethos** [globaltcad/sprouts#45]
The following code no longer compiles:
```java
Var<@Nullable String> var = Var.ofNullable(String.class, "Test");
var.set(null); // Does not compile
var.set(From.VIEW, null); // Also does not compile
```
We already encountered this problem in some form and I believe we
considered it a bug in the NullAway checker. Correct me if I am wrong but
it looks like NullAway can't handle generics properly...
It seems to be assuming that `T` is always non-null because the `set` methods do 
no longer have explicit `@Nullable` annotations on specific parameters.

I believe this is supported by this issue: https://github.com/uber/NullAway/issues/83

For us, this is a bit of a problem in practice.
I tried to introduce the most recent sprouts changes in SwingTree
and encountered multiple compile errors.
It is possible to circumvent them using `@SupressWarnings("NullAway")` 
in these few specific cases where a nullable object is passed to a `set` method...
...but I don't know if this is an acceptable approach for the Framework Tools.

On the other hand, introducing `@Nullable` would be a bit of a lie for most cases.
(Usually things don't need to be nullable, so why allow it?)

**Comment by Mazi-S** [comment]
I found this in `AbstractValue.java:27`
```
    protected @Nullable T _value;
```
which is wrong. The nullability should already be encoded in `T`.
Maybe fixing this will solve your problem.
I will look into it.

**Comment by Mazi-S** [comment]
I think we are doing it right and the problem is `NullAway` and I don't see a good solution to this problem :disappointed: 

I think we should stick to` JSpecify` and if clients use a checker that does not implement `JSpecify` correctly, its the clients responsibility?

Maybe we could use the following workarounds in SwingTree / Framework Tools:

```Java
@SuppressWarnings("NullAway")
private static <T extends  @Nullable Object> Var<T> set(Var<T> var, @Nullable T value) {
    return var.set(value);
}

@SuppressWarnings("NullAway")
private static <T extends  @Nullable Object> Var<T> set(Var<T> var, From from, @Nullable T value) {
    return var.set(from, value);
}
```

**Comment by Gleethos** [comment]
> I think we should stick to `JSpecify` and if clients use a checker that does not implement `JSpecify` correctly, its the clients responsibility?

I have been thinking about this a bit and also come to the same conclusion.
So I fully agree with keeping the sprouts API that way and then imposing the API
consumer to find a solution.

For now, I have used `@SuppressWarnings("NullAway")` everywhere directly in
SwingTree, but I like your proposal much more!
I guess for now we have to do it like that.
