### ISSUE TITLE
Non-nullable properties in nullable lists

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/sprouts#52]
Currently it is allowed to have a nullable `Vars` list with non-nullable `Var`'s.

I think we should always require matching nullability, because I think that is what is expected.

currently:
```Java
Var<String> var1 = Var.of("a");
Var<String> var2 = Var.of("b");
Var<String> nullable1 = Var.ofNullable(String.class, "a");
Var<String> nullable2 = Var.ofNullable(String.class, "b");

Vars<String> vars1 = Vars.of(var1, nullable1, var2);              // throws IllegalArgumentException
Vars<String> vars2 = Vars.ofNullable(nullable1, var1, nullable2); // is fine
```

This may lead to bugs:
```Java
if (vars2.allowsNull())
    vars2.at(1).set(null); // throws NullPointerException
```

**Comment by Gleethos** [comment]
I wholeheartedly agree.
I would definitely consider 
```java
if (vars2.allowsNull())
    vars2.at(1).set(null); // throws NullPointerException
```
to be a bug in case of `vars2` being declared as `Vars.ofNullable(nullable1, var1, nullable2)`.
That is both confusing and error prone.
It does not even fail predictably, it fails depending on the items!

So yes, this should be fixed.
